// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TournamentPlanner.Data;

#nullable disable

namespace TournamentPlanner.Data.Migrations.Tournaments
{
    [DbContext(typeof(TournamentDbContext))]
    [Migration("20260226183803_AddTournamentLifecycleAndProfiles")]
    partial class AddTournamentLifecycleAndProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TournamentPlanner.Data.Entities.Bout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ParticipantATotalScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParticipantAUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ParticipantBTotalScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParticipantBUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentDisciplineId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WinnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentDisciplineId", "ScheduledStartUtc");

                    b.HasIndex("WinnerUserId", "Status");

                    b.ToTable("Bouts");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.BoutRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoutId")
                        .HasColumnType("uuid");

                    b.Property<int>("ParticipantAScore")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantBScore")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoutId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("BoutRounds");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.Discipline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.ScoreEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwardedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwardedToUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoutRoundId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("BoutRoundId", "OccurredAtUtc");

                    b.ToTable("ScoreEvents");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("SignupEndDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SignupStartDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SignupEndDateUtc");

                    b.HasIndex("VenueId");

                    b.HasIndex("StartDateUtc", "EndDateUtc");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.TournamentDiscipline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BoutIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoundCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("TournamentId", "DisciplineId")
                        .IsUnique();

                    b.ToTable("TournamentDisciplines");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.TournamentMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "UserId", "Role")
                        .IsUnique();

                    b.ToTable("TournamentMembers");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.TournamentUserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("UserId");

                    b.ToTable("TournamentUserProfiles");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Country")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<double?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.Bout", b =>
                {
                    b.HasOne("TournamentPlanner.Data.Entities.TournamentDiscipline", "TournamentDiscipline")
                        .WithMany("Bouts")
                        .HasForeignKey("TournamentDisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TournamentDiscipline");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.BoutRound", b =>
                {
                    b.HasOne("TournamentPlanner.Data.Entities.Bout", "Bout")
                        .WithMany("Rounds")
                        .HasForeignKey("BoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bout");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.ScoreEvent", b =>
                {
                    b.HasOne("TournamentPlanner.Data.Entities.BoutRound", "BoutRound")
                        .WithMany("ScoreEvents")
                        .HasForeignKey("BoutRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoutRound");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.Tournament", b =>
                {
                    b.HasOne("TournamentPlanner.Data.Entities.Venue", "Venue")
                        .WithMany("Tournaments")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.TournamentDiscipline", b =>
                {
                    b.HasOne("TournamentPlanner.Data.Entities.Discipline", "Discipline")
                        .WithMany("TournamentDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TournamentPlanner.Data.Entities.Tournament", "Tournament")
                        .WithMany("Disciplines")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.TournamentMember", b =>
                {
                    b.HasOne("TournamentPlanner.Data.Entities.Tournament", "Tournament")
                        .WithMany("Members")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.Bout", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.BoutRound", b =>
                {
                    b.Navigation("ScoreEvents");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.Discipline", b =>
                {
                    b.Navigation("TournamentDisciplines");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.Tournament", b =>
                {
                    b.Navigation("Disciplines");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.TournamentDiscipline", b =>
                {
                    b.Navigation("Bouts");
                });

            modelBuilder.Entity("TournamentPlanner.Data.Entities.Venue", b =>
                {
                    b.Navigation("Tournaments");
                });
#pragma warning restore 612, 618
        }
    }
}
